SELECT
    "product_key"
    ,"product_name"
    ,"standard_cost"
    ,"color"
    ,"subcategory"
    ,"category"
    ,"background_color_format"
    ,"font_color_format"
FROM
    {{ref("products_cleaned")}}