SELECT
    "sales_order_number"
    ,"order_date"
    ,"order_date_year_month"
    ,"reseller_key"
    ,"employee_key"
    ,"sales_territory_key"
    ,"reseller_business_type"
    ,"reseller_name"
    ,"reseller_city"
    ,"reseller_state_province"
    ,"reseller_country"
    ,"employee_name_full"
    ,"employee_title"
    ,"employee_email"
    ,SUM(quantity) AS "quantity_sum"
    ,COUNT(DISTINCT "product_key") AS "cnt_distinct_products"
    ,SUM(sales_dollar) AS "sales_dollar_sum"
    ,SUM(cost_dollar) AS "cost_dollar_sum"
FROM 
    {{ref("sales_cleaned_enriched")}}
GROUP BY 
    "sales_order_number"
    ,"order_date"
    ,"order_date_year_month"
    ,"reseller_key"
    ,"employee_key"
    ,"sales_territory_key"
    ,"reseller_business_type"
    ,"reseller_name"
    ,"reseller_city"
    ,"reseller_state_province"
    ,"reseller_country"
    ,"employee_name_full"
    ,"employee_title"
    ,"employee_email"