
version: 2

models:
  - name: "_meteo"
    description: "Staging meteo data"
    columns:
      - name: "latitude"
        description: "Latitude of weather data"
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ["latitude", "longitude", "timezone", "time"]
  - name: "meteo_cleaned"
    description: "Cleaned version of raw meteo data"
    columns:
      - name: "temperature"
        description: "Temperature in Celsius"
        tests:
          - not_null